
version: '3.8'
services:
  application:
    build: ./
    container_name: 'cinema_base'
    ports: ['8080:8080']
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-app:5432/postgres_app_db'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=axweil'
  db:
    container_name: "postgres-app"
    image: 'postgres:14'
    ports: ['5432:5432']
    environment:
      - 'POSTGRES_DB=postgres_app_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=axweil'
  db-test:
    container_name: "postgres-test"
    image: 'postgres:14'
    ports: [ '5433:5433' ]
    environment:
      - 'POSTGRES_DB=postgres_test_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'